language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - docker
before_script:
  - docker-compose up -d database
script:
  - mvn --file pom.xml clean jacoco:prepare-agent package jacoco:report coveralls:report -P test-consumer,test-business
after_script:
  - mvn clean test jacoco:report coveralls:report
